name: Run Cron Jobs

on:
  schedule:
    - cron: '0 11 29 05 *' 
    - cron: '0 0 1 1 *'   
    - cron: '05 11 * * *'   
  workflow_dispatch:

jobs:
  run-cron-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run cron jobs
      run: node cronjobs.js
